# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Expose stdio interface
CMD ["node", "build/index.js"]
